apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: java-demo
  annotations:
    github.com/project-slug: pavankumarBL/java-demo
spec:
  type: other
  lifecycle: unknown
  owner: pavankumarBL
